//
//  Cusine.swift
//  BiteLog
//
//  Created by Nessa Kucuk, Turker on 5/18/25.
//
import Observation

enum Cuisine: String, CaseIterable, Identifiable {
    case american = "American"
    case italian = "Italian"
    case mexican = "Mexican"
    case chinese = "Chinese"
    case japanese = "Japanese"
    case thai = "Thai"
    case vietnamese = "Vietnamese"
    case korean = "Korean"
    case indian = "Indian"
    case french = "French"
    case greek = "Greek"
    case mediterranean = "Mediterranean"
    case middleEastern = "Middle Eastern"
    case spanish = "Spanish"
    case german = "German"
    case caribbean = "Caribbean"
    case cuban = "Cuban"
    case brazilian = "Brazilian"
    case peruvian = "Peruvian"
    case argentinian = "Argentinian"
    case southern = "Southern"
    case cajun = "Cajun"
    case creole = "Creole"
    case soulFood = "Soul Food"
    case barbecue = "Barbecue"
    case burger = "Burger"
    case pizza = "Pizza"
    case diner = "Diner"
    case deli = "Deli"
    case comfortFood = "Comfort Food"
    case breakfast = "Breakfast"
    case vegan = "Vegan"
    case vegetarian = "Vegetarian"
    case glutenFree = "Gluten-Free"
    case seafood = "Seafood"
    case steakhouse = "Steakhouse"
    case sushi = "Sushi"
    case ramen = "Ramen"
    case dimSum = "Dim Sum"
    case tapas = "Tapas"
    case texMex = "Tex-Mex"
    case hawaiian = "Hawaiian"
    case puertoRican = "Puerto Rican"
    case jewish = "Jewish"
    case kosher = "Kosher"
    case halal = "Halal"
    case irish = "Irish"
    case british = "British"
    case canadian = "Canadian"
    case quebecois = "Quebecois"
    case ethiopian = "Ethiopian"
    case moroccan = "Moroccan"
    case turkish = "Turkish"
    case russian = "Russian"
    case polish = "Polish"
    case filipino = "Filipino"
    case malaysian = "Malaysian"
    case singaporean = "Singaporean"
    case taiwanese = "Taiwanese"
    case hotPot = "Hot Pot"
    case asianFusion = "Asian Fusion"
    case modernAmerican = "Modern American"
    case gastropub = "Gastropub"
    case bakery = "Bakery"
    case cafe = "Cafe"
    case iceCream = "Ice Cream"
    case dessert = "Dessert"
    case foodTruck = "Food Truck"
    
    var id: String {
        return rawValue
    }
}
